### PR TITLE
fancystft updates

### PR DESCRIPTION
**Pull request by asness**

### CODE REVIEW

**Comment by jemaltieri** [comment]
Noice.

**Comment by asness** [comment]
I'm assuming nobody else is working on this right now, but if I'm wrong, shoot me an email.

This works better than it did, but it's still slow and I'm still having problems generating long files.  I'm working on a bigger revision to eliminate interpolation completely from the process (keeping Jem's more object-oriented approach, but doing interleaved analysis and synthesis, more like the PaulStretch script).  This makes the process an order of magnitude faster.

I'm also memory-mapping the arrays that store (potentially quite large) time-stretched band tracks before mixing.  I've seen that as a recommendation for dealing with large arrays, but I don't know too much about it, so if it's a bad idea please let me know.

I'm doing some testing right now and hope to share the changes tomorrow.

**Comment by jemaltieri** [comment]
Sweet! Looking forward to it. Curious to hear if taking out the interpolation changes the sound significantly, especially on longer stretches.

**Comment by asness** [comment]
I think it actually sounds better, for reasons that I'll describe in the update.  I'm going to close this pull request because the next one will supersede it.

**Pull request closed without merging**
